---
name: Canto
long_name: PomBase community curation tool
database_name: PomBase
database_url: 'http://www.pombase.org'
#instance_front_subtitle: Curate a paper for PomBase



Model::ChadoModel:
  connect_info:
    - dbi:Pg:dbname=pombase-build-2020-09-06;host=localhost
    - pbuild
    - pbuild
  schema_class: Canto::ChadoDB

instance_front_mhtml: /docs/pombase_instance_front.mhtml

instance_organism:
  taxonid: 4896

split_genotypes_by_organism: 0
diploid_mode: 1

annotation_figure_field: 0

"Model::TrackModel":
  schema_class: 'Canto::TrackDB'
  connect_info:
     - "dbi:SQLite:dbname=/var/pomcur/data/pombe_data/track.sqlite3"
data_directory: "/var/pomcur/data/pombe_data"

google_analytics_id: UA-19923239-2

implementation_classes:
  gene_adaptor: Canto::Chado::GeneLookup
  ontology_annotation_adaptor: Canto::Chado::OntologyAnnotationLookup
  interaction_annotation_adaptor: Canto::Chado::InteractionAnnotationLookup
  go_adaptor: Canto::Track::OntologyLookup
  ontology_adaptor: Canto::Track::OntologyLookup
  allele_adaptor: Canto::Chado::AlleleLookup

contact_email:
  address: helpdesk@pombase.org

email: 
  from_address: helpdesk@pombase.org
  admin_address: helpdesk@pombase.org
  admin_from_address: helpdesk@pombase.org
  reply_to: helpdesk@pombase.org
  noreply_address: noreply@pombase.org
  templates:
    session_accepted:
      subject: "email_templates/pombase/session_accepted_subject.mhtml"
      body: "email_templates/pombase/session_accepted_body.mhtml"
    session_assigned:
      subject: "email_templates/pombase/session_assigned_subject.mhtml"
      body: "email_templates/pombase/session_assigned_body.mhtml"
    session_resent:
      subject: "email_templates/pombase/session_resent_subject.mhtml"
      body: "email_templates/pombase/session_resent_body.mhtml"
    session_reassigned:
      subject: "email_templates/pombase/session_reassigned_subject.mhtml"
      body: "email_templates/pombase/session_reassigned_body.mhtml"
    reassigner:
      subject: "email_templates/pombase/reassigner_subject.mhtml"
      body: "email_templates/pombase/reassigner_body.mhtml"
    daily_summary:
      global: 1  # not an email about a particular session/publication
      subject: "email_templates/generic/daily_summary_subject.mhtml"
      body: "email_templates/generic/daily_summary_body.mhtml"



front_page_title: 'Welcome to Canto: the PomBase community curation tool'
front_page_template: local_templates/pombase_front_page.mhtml

extension_conf_files:
  - /var/pomcur/pombase-config/canto/annotation_ex_config/FYPO_A_E_config
  - /var/pomcur/pombase-config/canto/annotation_ex_config/GO_BP_A_E_config
  - /var/pomcur/pombase-config/canto/annotation_ex_config/GO_CC_A_E_config
  - /var/pomcur/pombase-config/canto/annotation_ex_config/GO_MF_A_E_config
  - /var/pomcur/pombase-config/canto/annotation_ex_config/PSI-MOD_A_E_config


# the "canto_root_subset" is created automatically
ontology_namespace_config:
  subsets_to_ignore:
    primary:
      - "is_a(Grouping_terms)"
      - "never_in_taxon(NCBITaxon:4896)"
    extension:
      - "is_a(canto_root_subset)"
      - "is_a(qc_do_not_annotate)"
  do_not_annotate_subsets:
    - "is_a(canto_root_subset)"
    - "is_a(qc_do_not_annotate)"
    - "is_a(gocheck_do_not_annotate)"
    - "is_a(gocheck_do_not_manually_annotate)"




cache:
  memcached:
    servers:
      - 127.0.0.1:11211


#canto_offline: 1

