name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: apt install libjson-xs-perl libtext-csv-xs-perl
      - name: Wait in case website isn't checked in yet
        run: sleep 120
      - name: Get website
        run: git clone --depth 1 https://github.com/pombase/website.git pombase-website
      - name: Run test script
        run: etc/check_config.pl
